/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cebitec.mgx.gui.login.configuration;

import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.NbPreferences;

public class MGXserverPanel extends javax.swing.JPanel implements DocumentListener {

    private final MGXserverOptionsPanelController controller;

    MGXserverPanel(MGXserverOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
        server.getDocument().addDocumentListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        server = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MGXserverPanel.class, "MGXserverPanel.jLabel1.text")); // NOI18N

        server.setText(org.openide.util.NbBundle.getMessage(MGXserverPanel.class, "MGXserverPanel.server.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(server, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        server.setText(NbPreferences.forModule(MGXserverPanel.class).get("server", ""));
    }

    void store() {
        NbPreferences.forModule(MGXserverPanel.class).put("server", server.getText());
    }

    boolean valid() {
        String content = server.getText();
        boolean ret = false;
        if (content.startsWith("http://") || content.startsWith("https://")) {
            //
            // remove protocol and extract fqdn
            //
            content = content.replaceFirst("http://", "");
            content = content.replaceFirst("https://", "");
            if (content.contains("/")) {
                content = content.split("/")[0];
            }
            if (content.length() == 0) {
                return false;
            }
            
            //
            // remove port
            //
            if (content.contains(":")) {
                content = content.split(":")[0];
            }
            
            //
            // try to resolve server name
            //
            try {
                InetAddress.getByName(content).getAddress();
                ret = true;
            } catch (UnknownHostException ex) {
            }
        }
        return ret;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField server;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent de) {
        controller.changed();
    }

    @Override
    public void removeUpdate(DocumentEvent de) {
        controller.changed();
    }

    @Override
    public void changedUpdate(DocumentEvent de) {
        controller.changed();
    }
}
