package de.cebitec.mgx.gui.attributevisualization;

import javax.swing.JComponent;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//de.cebitec.mgx.gui.attributevisualization//AttributeVisualization//EN",
autostore = false)
@TopComponent.Description(preferredID = "AttributeVisualizationTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "de.cebitec.mgx.gui.attributevisualization.AttributeVisualizationTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_AttributeVisualizationAction",
preferredID = "AttributeVisualizationTopComponent")
public final class AttributeVisualizationTopComponent extends TopComponent {

    public AttributeVisualizationTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(AttributeVisualizationTopComponent.class, "CTL_AttributeVisualizationTopComponent"));
        setToolTipText(NbBundle.getMessage(AttributeVisualizationTopComponent.class, "HINT_AttributeVisualizationTopComponent"));
        // forward group change events to the control panel
        groupingPanel1.addPropertyChangeListener(controlPanel1);
        // create initial group
        groupingPanel1.addGroup();
        controlPanel1.setTopComponent(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        groupingPanel1 = new de.cebitec.mgx.gui.attributevisualization.GroupingPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel1 = new de.cebitec.mgx.gui.attributevisualization.ControlPanel();
        chartpane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(groupingPanel1, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setDividerLocation(564);
        jSplitPane1.setDividerSize(5);
        jSplitPane1.setRightComponent(controlPanel1);

        chartpane.setMinimumSize(new java.awt.Dimension(800, 500));
        chartpane.setPreferredSize(new java.awt.Dimension(500, 500));
        jSplitPane1.setLeftComponent(chartpane);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chartpane;
    private de.cebitec.mgx.gui.attributevisualization.ControlPanel controlPanel1;
    private de.cebitec.mgx.gui.attributevisualization.GroupingPanel groupingPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
    
    void setVisualization(JComponent p) {
        chartpane.setViewportView(p);
    }
}
