/*
 * GroupingPanel.java
 *
 * Created on Dec 28, 2011, 2:27:49 PM
 */
package de.cebitec.mgx.gui.attributevisualization;

import de.cebitec.mgx.gui.attributevisualization.data.VisualizationGroup;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author sj
 */
public class GroupingPanel extends javax.swing.JPanel implements ActionListener {

    private int groupCount = 1;
    private List<GroupFrame> groupFrames = new ArrayList<GroupFrame>();

    /** Creates new form GroupingPanel */
    public GroupingPanel() {
        initComponents();
        addGroup.addActionListener(this);
        addGroupFrame(); // create initial group
    }

    public List<VisualizationGroup> getVisualizationGroups() {
        List<VisualizationGroup> ret = new ArrayList<VisualizationGroup>();
        for (GroupFrame g : groupFrames) {
            if (g.isActive()) {
                ret.add(g.getGroup());
            }
        }
        return ret;
    }

    private void addGroupFrame() {
        GroupFrame gf = new GroupFrame();
        gf.setGroupName("Group " + groupCount++);
        gf.setParent(this);
        groupFrames.add(gf);
        scrollpanel.add(gf);
    }

    void removeGroupFrame(GroupFrame gf) {
        groupFrames.remove(gf);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        addGroup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollpanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(300, 150));
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        addGroup.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        addGroup.setText("Add group");
        addGroup.setFocusable(false);
        addGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(addGroup);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        scrollpanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(scrollpanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel scrollpanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        addGroupFrame();
    }
}
