package de.cebitec.mgx.gui.goldstandard.wizards.selectjobs;

import de.cebitec.mgx.api.model.AttributeTypeI;
import de.cebitec.mgx.api.model.JobI;
import java.io.Serial;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionListener;

public final class SelectJobsVisualPanel1 extends JPanel {

    @Serial
    private static final long serialVersionUID = 1L;

    public static final String PROP_JOBS = "jobs";
    public static final String PROP_ATTRIBUTETYPE = "attribute_type";

    /**
     * Creates new form SelectSingleJobVisualPanel1
     */
    public SelectJobsVisualPanel1(Set<JobI> jobs, String selectJobString) {
        initComponents();

        selectJobLabel.setText(selectJobString);

        DefaultListModel<JobI> jobModel = new DefaultListModel<>();
        for (JobI job : jobs) {
            jobModel.addElement(job);
        }
        jobList.setModel(jobModel);
        jobList.setCellRenderer(new JobRenderer());

        attributeTypeBox.setRenderer(new AttributeTypeRenderer());

        clearSelections();
    }

    public void addListSelectionListener(ListSelectionListener lsl) {
        jobList.getSelectionModel().addListSelectionListener(lsl);
    }

    public List<JobI> getSelectedJobs() {
        return jobList.getSelectedValuesList();
    }

    public AttributeTypeI getSelectedAttributeType() {
        return (AttributeTypeI) attributeTypeBox.getSelectedItem();
    }

    public int getAttributeTypeListCount() {
        return attributeTypeBox.getItemCount();
    }

    public void setAttributeTypeList(List<AttributeTypeI> attrTypes) {
        Collections.sort(attrTypes);
        attributeTypeBox.removeAllItems();
        for (AttributeTypeI at : attrTypes) {
            attributeTypeBox.addItem(at);
        }
        if (!attrTypes.isEmpty()) {
            attributeTypeBox.setSelectedIndex(0);
        } else {
            attributeTypeBox.setSelectedIndex(-1);
        }
    }

    public void enableAttributeTypeBox(boolean enable) {
        attributeTypeBox.setEnabled(enable);
    }

    public void clearSelections() {
        jobList.getSelectionModel().clearSelection();
    }

    @Override
    public String getName() {
        return "Job selection";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jobList = new javax.swing.JList<>();
        attributeTypeBox = new javax.swing.JComboBox<>();
        selectJobLabel = new javax.swing.JLabel();
        atLabel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jobList);

        attributeTypeBox.setEnabled(false);

        selectJobLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(selectJobLabel, org.openide.util.NbBundle.getMessage(SelectJobsVisualPanel1.class, "SelectJobsVisualPanel1.selectJobLabel.text")); // NOI18N

        atLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(atLabel, org.openide.util.NbBundle.getMessage(SelectJobsVisualPanel1.class, "SelectJobsVisualPanel1.atLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(atLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attributeTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectJobLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(selectJobLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attributeTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atLabel;
    private javax.swing.JComboBox<AttributeTypeI> attributeTypeBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<JobI> jobList;
    private javax.swing.JLabel selectJobLabel;
    // End of variables declaration//GEN-END:variables

}
