notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: java

dist: bionic

sudo: required

jdk: oraclejdk11

branches:
  only:
    - MGX_gui_2_0

cache:
  directories:
  - $HOME/.m2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-compiler
  - sudo ln -s /usr/bin/protoc /usr/bin/protoc-3
  - git clone -b utilities_2_0 https://github.com/MGX-metagenomics/utilities.git
  - cd utilities && mvn clean install -DskipTests=true && cd .. && rm -rf utilities
  - git clone -b GPMS_2_0 https://github.com/MGX-metagenomics/GPMS.git
  - cd GPMS && mvn clean install -DskipTests=true && cd .. && rm -rf GPMS
  - git clone -b MGX_client_2_0 https://github.com/MGX-metagenomics/MGX-client.git
  - cd MGX-client && mvn clean install -DskipTests=true && cd .. && rm -rf MGX-client

install: true

script:
  - mvn clean install
