package de.cebitec.mgx.gui.wizard.sample;

import com.github.lgooddatepicker.components.CalendarPanel;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.optionalusertools.CalendarListener;
import com.github.lgooddatepicker.zinternaltools.CalendarSelectionEvent;
import com.github.lgooddatepicker.zinternaltools.YearMonthChangeEvent;

import javax.swing.*;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;


public final class SampleVisualPanel1 extends JPanel  {

    public static final String PROP_COLLECTIONDATE = "collection_date";

    /**
     * Creates new form SampleVisualPanel1
     */
    public SampleVisualPanel1() {
        initComponents();

        panel.addCalendarListener(new CalendarListener() {
            @Override
            public void selectedDateChanged(CalendarSelectionEvent event) {
                panel.firePropertyChange(PROP_COLLECTIONDATE, 0, 1);

            }

            @Override
            public void yearMonthChanged(YearMonthChangeEvent event) {
                panel.firePropertyChange(PROP_COLLECTIONDATE, 0, 1);
            }

        });
    }

    @Override
    public String getName() {
        return "Collection date";
    }

    public Date getCollectionDate() {
        LocalDate d = panel.getSelectedDate();
        return Date.from(d.atStartOfDay(ZoneId.systemDefault()).toInstant());
    }

    public void setCollectionDate(Date d) {
        LocalDate date = d.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        panel.setSelectedDate(date);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        final LocalDate today = LocalDate.now();
        final LocalDate date = LocalDate.of(1970, Month.JANUARY, 1);
        Locale locale = new Locale("en");
        DatePickerSettings dateSettings = new DatePickerSettings(locale);
        dateSettings.setFirstDayOfWeek(DayOfWeek.MONDAY);
        dateSettings.setFormatForDatesCommonEra("dd-MM-yyyy");
        dateSettings.setFormatForDatesBeforeCommonEra("uuuu-MM-dd");
        dateSettings.setAllowKeyboardEditing(false);
        dateSettings.setVisibleClearButton(false);
        dateSettings.setVisibleNextMonthButton(true);
        panel = new CalendarPanel(dateSettings);
        panel.setSelectedDate(today);
        panel.setToolTipText("Select Date");
        dateSettings.setDateRangeLimits(date, today);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SampleVisualPanel1.class, "SampleVisualPanel1.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private CalendarPanel panel;
    // End of variables declaration//GEN-END:variables
}
