package de.cebitec.mgx.gui.wizard.sample;

import javax.swing.JPanel;

public final class SampleVisualPanel2 extends JPanel {

    public static final String PROP_MATERIAL = "material";
    public static final String PROP_TEMPERATURE = "temperature";
    public static final String PROP_VOLUME = "volume";
    public static final String PROP_VOLUME_UNIT = "volume_unit";

    /** Creates new form SampleVisualPanel2 */
    public SampleVisualPanel2() {
        initComponents();
        tempUnit.addItem("F");
        tempUnit.addItem("C");
        tempUnit.addItem("K");
        tempUnit.setEditable(false);
        tempUnit.setSelectedItem("C");
        volUnit.addItem("ml");
        volUnit.addItem("l");
        volUnit.addItem("g");
        volUnit.addItem("kg");
        volUnit.setEditable(false);
        volUnit.setSelectedItem("ml");
    }

    public String getMaterial() {
        return material.getText();
    }

    public void setMaterial(String m) {
        material.setText(m);
    }

    public int getTemperature() {
        int t = Integer.parseInt(temperature.getText());
        // FIXME: convert to K, depending on tempUnit
        return t;
    }
    
    public void setTemperature(Integer t) {
        temperature.setText(t.toString());
    }

    public int getVolume() {
        int vol = Integer.parseInt(volume.getText());
        return vol;
    }
    
    public void setVolume(Integer vol) {
        volume.setText(vol.toString());
    }

    public String getVolumeUnit() {
        return (String) volUnit.getSelectedItem();
    }
    
    public void setVolumeUnit(String vu) {
        // FIXME
    }

    @Override
    public String getName() {
        return "Sample description";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        material = new javax.swing.JTextField();
        temperature = new javax.swing.JTextField();
        volume = new javax.swing.JTextField();
        tempUnit = new javax.swing.JComboBox();
        volUnit = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SampleVisualPanel2.class, "SampleVisualPanel2.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(SampleVisualPanel2.class, "SampleVisualPanel2.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(SampleVisualPanel2.class, "SampleVisualPanel2.jLabel3.text")); // NOI18N

        material.setText(org.openide.util.NbBundle.getMessage(SampleVisualPanel2.class, "SampleVisualPanel2.material.text")); // NOI18N

        temperature.setText(org.openide.util.NbBundle.getMessage(SampleVisualPanel2.class, "SampleVisualPanel2.temperature.text")); // NOI18N

        volume.setText(org.openide.util.NbBundle.getMessage(SampleVisualPanel2.class, "SampleVisualPanel2.volume.text")); // NOI18N

        tempUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        volUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(material, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(volume)
                            .addComponent(temperature, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tempUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField material;
    private javax.swing.JComboBox tempUnit;
    private javax.swing.JTextField temperature;
    private javax.swing.JComboBox volUnit;
    private javax.swing.JTextField volume;
    // End of variables declaration//GEN-END:variables
}
