package de.cebitec.mgx.gui.wizard.seqrun;

import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;


public final class SeqRunVisualPanel3 extends JPanel {

    public static final String PROP_QTHRESHOLD = "quality_threshold";
    public static final String PROP_MINOVERLAP = "min_overlap";
    public static final String PROP_MAXMISMATCHES = "max_mismatches";    

    /**
     * Creates new form SeqRunVisualPanel3
     */
    public SeqRunVisualPanel3() {        
        initComponents();
        qualityThresholdSlider.addChangeListener(new SliderListener(PROP_QTHRESHOLD));
        minimalOverlapSlider.addChangeListener(new SliderListener(PROP_MINOVERLAP));
        maximalMismatchesSlider.addChangeListener(new SliderListener(PROP_MAXMISMATCHES));
    }

    @Override
    public String getName() {
        return "Paired-End parameters";
    }

    public int getQualityThreshold() {
        return qualityThresholdSlider.getValue();
    }
    
    public int getMinimalOverlap() {
        return minimalOverlapSlider.getValue();
    }
    
    public float getMaximalMismatches() {
        return maximalMismatchesSlider.getValue() / 100f;
    }

    public void setQualityThreshold(int qt) {
        qualityThresholdSlider.setValue(qt);
    }
    
    public void setMinimalOverlap(int mo) {
        minimalOverlapSlider.setValue(mo);
    }
    
    public void setMaximalMismatches(float mm) {
        maximalMismatchesSlider.setValue((int) (mm * 100));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qualityThresholdLabel = new javax.swing.JLabel();
        minimalOverlapLabel = new javax.swing.JLabel();
        maximalMismatchesLabel = new javax.swing.JLabel();
        qualityThresholdSlider = new javax.swing.JSlider();
        minimalOverlapSlider = new javax.swing.JSlider();
        maximalMismatchesSlider = new javax.swing.JSlider();

        org.openide.awt.Mnemonics.setLocalizedText(qualityThresholdLabel, org.openide.util.NbBundle.getMessage(SeqRunVisualPanel3.class, "SeqRunVisualPanel3.qualityThresholdLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(minimalOverlapLabel, org.openide.util.NbBundle.getMessage(SeqRunVisualPanel3.class, "SeqRunVisualPanel3.minimalOverlapLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maximalMismatchesLabel, org.openide.util.NbBundle.getMessage(SeqRunVisualPanel3.class, "SeqRunVisualPanel3.maximalMismatchesLabel.text")); // NOI18N

        qualityThresholdSlider.setMaximum(60);
        qualityThresholdSlider.setValue(20);
        qualityThresholdSlider.setName("qualityThresholdSlider"); // NOI18N

        minimalOverlapSlider.setValue(10);
        minimalOverlapSlider.setName("minimalOverlapSlider"); // NOI18N

        maximalMismatchesSlider.setValue(5);
        maximalMismatchesSlider.setName("maximalMismatchesSlider"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maximalMismatchesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximalMismatchesSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(minimalOverlapLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimalOverlapSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(qualityThresholdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qualityThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qualityThresholdLabel)
                    .addComponent(qualityThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimalOverlapLabel)
                    .addComponent(minimalOverlapSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maximalMismatchesLabel)
                    .addComponent(maximalMismatchesSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        qualityThresholdSlider.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(SeqRunVisualPanel3.class, "SeqRunVisualPanel3.qualityThresholdSlider.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel maximalMismatchesLabel;
    private javax.swing.JSlider maximalMismatchesSlider;
    private javax.swing.JLabel minimalOverlapLabel;
    private javax.swing.JSlider minimalOverlapSlider;
    private javax.swing.JLabel qualityThresholdLabel;
    private javax.swing.JSlider qualityThresholdSlider;
    // End of variables declaration//GEN-END:variables

    private final class SliderListener implements ChangeListener {
        String property;
        
        public SliderListener(String property) {
            this.property = property;
        }
                
        @Override
        public void stateChanged(ChangeEvent e) {
            firePropertyChange(property, 0, 1);
        }        
    }
}