package de.cebitec.mgx.gui.wizard.seqrun;

import de.cebitec.mgx.api.groups.FileType;
import de.cebitec.mgx.gui.swingutils.util.SuffixFilter;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.openide.util.NbPreferences;

public final class SeqRunVisualPanel2 extends JPanel {

    public static final String PROP_FORWARD = "seqfile_forward";
    public static final String PROP_REVERSE = "seqfile_reverse";
    private File file = null;
    private String header;
    private boolean forward;

    /**
     * Creates new form SeqRunVisualPanel2
     * @param header String for the header of the panel
     */
    public SeqRunVisualPanel2(String header, boolean seqfileForward) {
        initComponents();
        String last = NbPreferences.forModule(JFileChooser.class).get("lastDirectory", null);
        if (last != null) {
            File f = new File(last);
            if (f.exists() && f.isDirectory()) {
                fchooser.setCurrentDirectory(f);
            }
        }

        fchooser.addChoosableFileFilter(new SuffixFilter(FileType.FAS));
        fchooser.addChoosableFileFilter(new SuffixFilter(FileType.FASGZ));
        fchooser.addChoosableFileFilter(new SuffixFilter(FileType.FASTQ));
        fchooser.addChoosableFileFilter(new SuffixFilter(FileType.FASTQGZ));
        fchooser.addChoosableFileFilter(new SuffixFilter(FileType.SFF));

        this.header = header;
        this.forward = seqfileForward;
        
        if (forward)
            fchooser.addPropertyChangeListener(new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent evt) {
                    if ("SelectedFileChangedProperty".equals(evt.getPropertyName())) {
                        NbPreferences.forModule(JFileChooser.class).put("lastDirectory", fchooser.getCurrentDirectory().getAbsolutePath().toString());
                        file = fchooser.getSelectedFile();
                        firePropertyChange(PROP_FORWARD, 0, 1);
                    }
                }
            });
        else
            fchooser.addPropertyChangeListener(new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent evt) {
                    if ("SelectedFileChangedProperty".equals(evt.getPropertyName())) {
                        NbPreferences.forModule(JFileChooser.class).put("lastDirectory", fchooser.getCurrentDirectory().getAbsolutePath().toString());
                        file = fchooser.getSelectedFile();
                        firePropertyChange(PROP_REVERSE, 0, 1);
                    }
                }
            });        
    }

    public SeqRunVisualPanel2() {
        this("Select sequence data", true);
    }
    
    @Override
    public String getName() {
        return header;
    }
    
    @Override
    public void setName(String header) {
        this.header = header;
    }

    public File getSelectedFile() {
        return file;
    }
    
    public boolean isForward(){
        return forward;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchooser = new javax.swing.JFileChooser();

        fchooser.setControlButtonsAreShown(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fchooser;
    // End of variables declaration//GEN-END:variables
}
