package de.cebitec.mgx.gui.attributevisualization.ui;

import javax.swing.JComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.windows.Mode;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//de.cebitec.mgx.gui.attributevisualization.ui//AttributeVisualization//EN",
autostore = false)
@TopComponent.Description(preferredID = "AttributeVisualizationTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "de.cebitec.mgx.gui.attributevisualization.ui.AttributeVisualizationTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_AttributeVisualizationAction",
preferredID = "AttributeVisualizationTopComponent")
public final class AttributeVisualizationTopComponent extends TopComponent {

    public AttributeVisualizationTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(AttributeVisualizationTopComponent.class, "CTL_AttributeVisualizationTopComponent"));
        setToolTipText(NbBundle.getMessage(AttributeVisualizationTopComponent.class, "HINT_AttributeVisualizationTopComponent"));
        // forward group change events to the control panel
//        groupingPanel1.addPropertyChangeListener(controlPanel1);
        // create initial group
//        groupingPanel1.addGroup();
        controlPanel1.setTopComponent(this);
        openVGroupTopComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel1 = new de.cebitec.mgx.gui.attributevisualization.ui.ControlPanel();
        chartpane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(564);
        jSplitPane1.setDividerSize(5);

        controlPanel1.setMaximumSize(new java.awt.Dimension(200, 32767));
        controlPanel1.setPreferredSize(new java.awt.Dimension(200, 504));
        jSplitPane1.setRightComponent(controlPanel1);

        chartpane.setMinimumSize(new java.awt.Dimension(800, 500));
        chartpane.setPreferredSize(new java.awt.Dimension(500, 500));
        jSplitPane1.setLeftComponent(chartpane);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chartpane;
    private de.cebitec.mgx.gui.attributevisualization.ui.ControlPanel controlPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
        controlPanel1.dispose();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    public void setVisualization(JComponent p) {
        chartpane.setViewportView(p);
    }

    private void openVGroupTopComponent() {
        VisualizationGroupTopComponent pe = Lookup.getDefault().lookup(VisualizationGroupTopComponent.class);
        pe.setVisible(true);

        Mode m = WindowManager.getDefault().findMode("output");
        if (m != null) {
            m.dockInto(pe);
        } else {
            System.err.println("output mode not found");
        }
        pe.open();
        
        //pe.requestActive();
    }
}
