package de.cebitec.mgx.gui.goldstandard.ui.charts.pipelinecomparison;

/**
 *
 * @author pblumenk
 */
public class PCDistanceViewCustomizer extends javax.swing.JPanel{

    /**
     * Creates new form TableViewCustomizer
     */
    public PCDistanceViewCustomizer() {
        initComponents();
    }       

public boolean normalizeVectors(){
    return normalizeVectors.isSelected();
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        normalizeVectors = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(normalizeVectors, "normalize vectors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(normalizeVectors)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(normalizeVectors)
                .addContainerGap(330, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox normalizeVectors;
    // End of variables declaration//GEN-END:variables
}
