/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cebitec.mgx.gui.wizard.mapping;

import de.cebitec.mgx.api.model.JobParameterI;
import de.cebitec.mgx.gui.mapping.MappingCtx;
import java.util.List;

/**
 *
 * @author sjaenick
 */
public class MappingPanel extends javax.swing.JPanel {

    /**
     * Creates new form MappingPanel
     */
    public MappingPanel() {
        initComponents();
    }

    public void setMapping(MappingCtx ctx) {
        ref.setText(ctx.getReference().getName());

        String[] elems = new String[ctx.getRuns().length];
        for (int i = 0; i < elems.length; i++) {
            elems[i] = ctx.getRuns()[i].getName();
        }
        String runNames = String.join(", ", elems);
        run.setText(runNames);
        tool.setText(ctx.getTool().getName());

        List<JobParameterI> parameters = ctx.getJob().getParameters();
        if (parameters != null && !parameters.isEmpty()) {
            StringBuilder sb = new StringBuilder();
            for (JobParameterI jp : parameters) {
                if (!jp.getClassName().contains("GetMGXReference")) {
                    sb.append(jp.getUserName());
                    sb.append(": ");
                    sb.append(jp.getParameterValue());
                    sb.append(System.lineSeparator());
                }
            }
            params.setText(sb.toString());
        } else {
            params.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        run = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tool = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ref = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        params = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MappingPanel.class, "MappingPanel.jLabel1.text")); // NOI18N

        run.setEditable(false);
        run.setText(org.openide.util.NbBundle.getMessage(MappingPanel.class, "MappingPanel.run.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MappingPanel.class, "MappingPanel.jLabel2.text")); // NOI18N

        tool.setEditable(false);
        tool.setText(org.openide.util.NbBundle.getMessage(MappingPanel.class, "MappingPanel.tool.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(MappingPanel.class, "MappingPanel.jLabel3.text")); // NOI18N

        ref.setEditable(false);
        ref.setText(org.openide.util.NbBundle.getMessage(MappingPanel.class, "MappingPanel.ref.text")); // NOI18N

        params.setEditable(false);
        params.setBackground(new java.awt.Color(238, 238, 238));
        params.setColumns(20);
        params.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        params.setRows(5);
        jScrollPane1.setViewportView(params);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(MappingPanel.class, "MappingPanel.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ref)
                    .addComponent(run)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(tool))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(77, 100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea params;
    private javax.swing.JTextField ref;
    private javax.swing.JTextField run;
    private javax.swing.JTextField tool;
    // End of variables declaration//GEN-END:variables
}
