/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cebitec.mgx.gui.devel;

import java.io.Serial;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//de.cebitec.mgx.gui.devel//LookupBrowser//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "LookupBrowserTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "satellite", openAtStartup = false)
@ActionID(category = "Window", id = "de.cebitec.mgx.gui.devel.LookupBrowserTopComponent")
@ActionReference(path = "Menu/Window", position = 555)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_LookupBrowserAction",
        preferredID = "LookupBrowserTopComponent"
)
@Messages({
    "CTL_LookupBrowserAction=LookupBrowser",
    "CTL_LookupBrowserTopComponent=LookupBrowser Window",
    "HINT_LookupBrowserTopComponent=This is a LookupBrowser window"
})
public final class LookupBrowserTopComponent extends TopComponent implements LookupListener {

    @Serial
    private static final long serialVersionUID = 1L;

    private final Lookup lkp;
    private final Lookup.Result<Object> res;

    public LookupBrowserTopComponent() {
        initComponents();
        setName(Bundle.CTL_LookupBrowserTopComponent());
        setToolTipText(Bundle.HINT_LookupBrowserTopComponent());

        lkp = Utilities.actionsGlobalContext();
        res = lkp.lookupResult(Object.class);
        res.addLookupListener(this);
    }

    @Override
    public void resultChanged(LookupEvent ev) {
        jTextArea1.setText("");
        StringBuilder sb = new StringBuilder();
        for (Object o : res.allInstances()) {
            if (o.getClass().getPackage().getName().contains("mgx")) {
                sb.append(o.toString());
                sb.append(System.lineSeparator());
            }
        }
        jTextArea1.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
