package de.cebitec.mgx.gui.wizard.habitatold;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class HabitatWizardVisualPanel2 extends JPanel implements DocumentListener {

    public static final String PROP_NAME = "name";
    public static final String PROP_DESCRIPTION = "description";
    public static final String PROP_BIOME = "biome";

    /** Creates new form HabitatWizardVisualPanel2 */
    public HabitatWizardVisualPanel2() {
        initComponents();
        habBiome.getDocument().addDocumentListener(this);
        habDescription.getDocument().addDocumentListener(this);
        habName.getDocument().addDocumentListener(this);
    }

    @Override
    public String getName() {
        return "Habitat description";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        habName = new javax.swing.JTextField();
        habBiome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        habDescription = new javax.swing.JTextArea();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(HabitatWizardVisualPanel2.class, "HabitatWizardVisualPanel2.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(HabitatWizardVisualPanel2.class, "HabitatWizardVisualPanel2.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(HabitatWizardVisualPanel2.class, "HabitatWizardVisualPanel2.jLabel3.text")); // NOI18N

        habName.setText(org.openide.util.NbBundle.getMessage(HabitatWizardVisualPanel2.class, "HabitatWizardVisualPanel2.habName.text")); // NOI18N

        habBiome.setText(org.openide.util.NbBundle.getMessage(HabitatWizardVisualPanel2.class, "HabitatWizardVisualPanel2.habBiome.text")); // NOI18N

        habDescription.setColumns(20);
        habDescription.setRows(5);
        jScrollPane1.setViewportView(habDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(habBiome, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(habName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(habName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(habBiome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField habBiome;
    private javax.swing.JTextArea habDescription;
    private javax.swing.JTextField habName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        if (habName.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_NAME, 0, 1);
        }
        if (habBiome.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_BIOME, 0, 1);
        }
        if (habDescription.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_DESCRIPTION, 0, 1);
        }
    }

    public String getHabitatName() {
        return habName.getText();
    }

    public String getBiome() {
        return habBiome.getText();
    }

    public String getDescription() {
        return habDescription.getText();
    }
}
