package de.cebitec.mgx.gui.goldstandard.ui;

import de.cebitec.mgx.api.groups.ImageExporterI;
import de.cebitec.mgx.gui.goldstandard.ui.charts.EvaluationViewerI;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//de.cebitec.mgx.gui.goldstandard.ui//Evaluation//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "EvaluationTopComponent",
        iconBase = "de/cebitec/mgx/gui/goldstandard/ui/icon.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "de.cebitec.mgx.gui.goldstandard.ui.EvaluationTopComponent")
@ActionReferences({
    @ActionReference(path = "Menu/Window", position = 342),
    @ActionReference(path = "Toolbars/UndoRedo", position = 560)
})
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EvaluationAction",
        preferredID = "EvaluationTopComponent"
)
@Messages({
    "CTL_EvaluationAction=Evaluate pipelines",
    "CTL_EvaluationTopComponent=Evaluate pipelines",
    "HINT_EvaluationTopComponent=Tool for a fast evaluation of pipelines"
})
public final class EvaluationTopComponent extends TopComponent {
    
    private final Lookup lookup;
    private final InstanceContent content = new InstanceContent();
    
    private ImageExporterI exporter;    
    
    public EvaluationTopComponent() {
        initComponents();
        setName(Bundle.CTL_EvaluationTopComponent());
        setToolTipText(Bundle.HINT_EvaluationTopComponent());
        
        int width = jSplitPane1.getSize().width;
        jSplitPane1.setDividerLocation(width - 50);
        lookup = new AbstractLookup(content);
        associateLookup(lookup);
        jSplitPane1.setRightComponent(new EvaluationControlPanel(this));
        chartpane.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        chartpane = new javax.swing.JScrollPane();

        jSplitPane1.setDividerSize(5);
        jSplitPane1.setResizeWeight(0.9);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(850, 700));

        chartpane.setMinimumSize(new java.awt.Dimension(600, 400));
        jSplitPane1.setLeftComponent(chartpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chartpane;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }
    
    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }
    
    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }
    
    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
    
    public void setVisualization(EvaluationViewerI v) {
        if (v == null) {
            chartpane.setViewportView(null);
            if (exporter != null) {
                content.remove(exporter);
            }
            exporter = null;
        } else {
            chartpane.setViewportView(v.getComponent());
            exporter = v.getImageExporter();
            if (exporter != null && exporter.getSupportedTypes().length > 0) {
                content.add(exporter);
            }
        }
    }
}
