/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cebitec.mgx.gui.swingutils;

import de.cebitec.mgx.api.groups.ImageExporterI;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.Serial;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author sjaenick
 */
public class DelayedPlot extends javax.swing.JPanel {

    @Serial
    private static final long serialVersionUID = 1L;
    
    private ImageExporterI exporter = null;

    /**
     * Creates new form DelayedPlot
     */
    public DelayedPlot() {
        initComponents();
    }

    public void setTarget(JComponent target, ImageExporterI exporter) {
        this.exporter = exporter;
        Dimension mySize = getSize();
        removeAll();
        setLayout(new BorderLayout());
        if (target != null) {
            Dimension tSize = target.getSize();
            if (tSize.getHeight() > mySize.getHeight() || tSize.getWidth() > mySize.getWidth()) {
                JScrollPane pane = new JScrollPane();
                pane.setViewportView(target);
                if (tSize.getHeight() > mySize.getHeight())
                    pane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
                if (tSize.getWidth() > mySize.getWidth())
                    pane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
                add(pane, BorderLayout.CENTER);
            } else {
                add(target, BorderLayout.CENTER);
            }
        } else {
            add(new JLabel("An error occurred."), BorderLayout.NORTH);
        }
        revalidate();
    }

    public ImageExporterI getImageExporter() {
        return exporter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DelayedPlot.class, "DelayedPlot.jLabel1.text")); // NOI18N

        jProgressBar1.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
